<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Chat</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="/css/chat.css">
        <script src="http://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="/js/chat.js"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div id="top-container" class="row">
                <script>
                    var initialMessages = <?= json_encode($messages); ?>;
                </script>
                <div id="message-window" class="col-xs-9">
                </div>

                <div id="users-list" class="col-xs-3">
                    <?php foreach ($onlineUsers as $user): ?>
                        <div><?= $user['username']; ?></div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div id="bottom-container" class="row">
                <textarea id="message" class="col-xs-9"></textarea>
                <button id="send-message" class="col-xs-3">Send &rarr;</button>
            </div>
        </div>
    </body>
</html>
