<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>LOGIN FORM</h2>
<div id="SignUpDiv">
    <form method="POST" action="/index.php?action=login">
        <?php
        if (!empty($_SESSION['errorMessage'])) {
            echo '<div style="color:#F00; font-weight:bold; font-size:20px;">' . $_SESSION['errorMessage'] .'</div>';
            unset($_SESSION['errorMessage']);
        }
        ?>
        <table>
            <tr>
                <td>Your username</td>
                <td><input type="text" name="username"/></td>
            </tr>
            <tr>
                <td>Password :</td>
                <td><input type="password" name="password"/></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Login"/></td>
            </tr>
        </table>
    </form>
</div>
</body>
</html>
